#! /usr/bin/env sh 

# -------------------------------------------------
# Filename:    zsh
# Description: Installing zsh and oh-my-zsh 
# Maintainer:  @fdsolutions <https://github.com/fdsolutions>
# -------------------------------------------------

source ${DOTFILES_DIR}"/zsh/default.vars"
source ${DOTFILES_DIR}"/includes/libs/bashful/bin/bashful-messages"


# Installing  ZSH 

if [[ -f /usr/local/bin/zsh ]]; then 
	info "ZSH is already installed" 
else 
	brew install zsh 
fi;

# Installing OH-MY-ZSH 

if [[ -d $HOME/.oh-my-zsh ]]; then 
	info "OH-MY-ZSH is already installed" 
else 
	curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi;




